### ISSUE TITLE
.sublime-completions disabled when CodeComplice is present

### ISSUE THREAD

**Issue by mrliptontea** [spectacles/CodeComplice#13]
Hi,

I've noticed that if I have installed CodeComplice and completions package, e.g. "PHP Completions Kit", these completions are not appearing in Sublime's standard autocomplete (<kbd>Ctrl</kbd>+<kbd>Space</kbd>).
I like to use this package because these completions are not included in PECL catalog.

When I remove CodeComplice completely from Packages folder, PHP Completions become available. 

It seems that it does not matter if I remove PHP from `codeintel_enabled_languages` or set `codeintel` setting to `false`.

Can this issue be resolved in some simple way?

**Comment by mrliptontea** [comment]
Ok, my bad, I've noticed `Adding php-5.5 stdlib` in the console and standard PHP completions work pretty well.

But it still be nice if `.sublime-completions` wouldn't disappear when using CodeComplice.

**Comment by spectacles** [comment]
thanx for the attention! Your (<kbd>Ctrl</kbd>+<kbd>Space</kbd>) will be showing `.sublime-completions` starting from next version!
