### ISSUE TITLE
Change tooltip display

### ISSUE THREAD

**Issue by PixelT** [spectacles/CodeComplice#18]
As example below:
https://github.com/marijnh/tern_for_sublime/pull/61

**Comment by PixelT** [comment]
Hi @wizza-smile - any feedback / info about this proposal? :)

**Comment by wizza-smile** [comment]
we are excepting pull requests! ;)

**Comment by PixelT** [comment]
I'm not sure if I understood you good :)
I create this topic to suggest a feature to add in CodeComplice.
I can't pull request because I'm not a python programmer :)

**Comment by wizza-smile** [comment]
Python is easy and a lot of fun!

**Comment by spectacles** [comment]
yeah, you should give it a try!
