### ISSUE TITLE
Plugin doesn't work now...

### ISSUE THREAD

**Issue by PixelT** [spectacles/CodeComplice#19]
The tooltip doesn't wan't to display...
- I try to delete the .codeintel folder
- I try the plugin on fresh ST installation (only ST + CodeComplice)
When I try to 'run' autocomplete (ctrl + shift + space) in console I have:
processing `JavaScript': please wait...
current triggername: 'javascript-complete-object-members'
end nothing happens....

Edit.
I downloaded the version 1.1.0 from releases, and they work OK - the 1.1.1 version not
Testes on ST 3 Build 3070

**Comment by spectacles** [comment]
I've supposedly fixed this and re-released 1.1.1!
Can you please re-install from packagecontrol and confirm it is working now?!

Thanx for reporting!

**Comment by PixelT** [comment]
After reinstal 1.1.1 the autocomplete works now - thanks!
One small things can be fact, that after install CodeComplice, my ST was crashed....
I have no certainty whether it is caused by CC, but I install it 2 times, ST crashed 2 times always after finish install (I must restart ST manually then)

**Comment by PixelT** [comment]
@spectacles 
Now I'm reinstall the CodeComplice, and they don't work now in js files... :(

**Comment by spectacles** [comment]
Nothing, not the tiniest bit has changed since your last comment!

**Comment by PixelT** [comment]
OK, I have new information in this subject.
( | is mouse caret )

Autocomplete doesn't show:
```
$( document ).ready(function() {
		var lightbox = $('figure.lightbox-image');
		lightbox.picture();

		var xxx = 'example string';
		xxx.|
});
```

Autocomplete show:
```
$( document ).ready(function() {
		var xxx = 'example string';
		xxx.|

		var lightbox = $('figure.lightbox-image');
		lightbox.picture();
});
```

The picture() is a method from other (external) library.
When I comment the line lightbox.picture() the autocomplete popup will be show, so I think the external function call stops / breaks plugin work?

**Comment by spectacles** [comment]
Yes it's true, Komodo's JavaScript lexer/parser gets easily confused!
