### ISSUE TITLE
CSS tooltips doesn't work?

### ISSUE THREAD

**Issue by PixelT** [spectacles/CodeComplice#20]
When I write ( | is cursor position ) in CSS file:
```
position: | 
```
and press to show autocomplete ( ctrl + shift + space ) - nothing display...
When I press space + shift, they display options (relative, fixed, absolute etc.)

In the other side, when I have code in HTML/PHP file:
```
<div class="some-class" | >
```
the tooltip display (attributes) when I press ctrl + space or ctrl + shift + space...

**Comment by wizza-smile** [comment]
quite frankly: you should remove CSS from "codeintel_enabled_languages"! Sublime's own css completions are just as good or better than Komodo's. 

You should also consider this thread: 
https://www.sublimetext.com/forum/viewtopic.php?f=3&t=15037
