### ISSUE TITLE
[Bug] Goto Definition class extended

### ISSUE THREAD

**Issue by ptcong** [spectacles/CodeComplice#21]
@wizza-smile 
I prefer to use CodeComplice Goto Definition, (goto_python_definition command) than ST Goto Definition. 
Today i catch a bug while go to definition of class Extended.
Select `Collection` and choose **Jump to Symbol Definition** context menu, instead of open Collection class, it open SesssionInterface file.

```php
class Session extends Collection implements SessionInterface
{
}
```
Please resolve this

**Comment by wizza-smile** [comment]
you can find the fix in the latest comment. thanx for reporting!
