### ISSUE TITLE
Ruby autocompletion don't work

### ISSUE THREAD

**Issue by xskif** [spectacles/CodeComplice#25]
There is no autocompletion at all.

When i typing `1.` i want to see all methods like `abs`, `abs2`, `ago`, etc... But i need to trigger this manually.

Autcomopletetion work if i start typing first letters of method e.g. `Time.n`, but tooltip also offers me none Time object methods or functions, like this:
```ruby
    Time.namespace :say_controller do
      
    end
```
Time don't have `namespace` method at all. It's a cross-language bug of plugin.

Also, when i typing chaining method calls, completion dosen't work, even manual, e.g. i have expression `1.hour.from_now`, i'm expect some completion when i type `1.hour.f`(`hour` is a method, not property)

**Comment by xskif** [comment]
Just try to manually trigger completion right after dot, and this shows me only `Time` methods.

**Comment by xskif** [comment]
Funny. SublimeCodeIntel works well. =)

**Comment by spectacles** [comment]
hey, I added a fix which will make the popupTrigger work again! 
I just tested and it's working for me in both cases `Time.` and `1.` . 

`1.hour.from_now` is a Rails function and cannot work from Ruby alone. CodeComplice offers the Komodo "Rails" catalog which is for version 1.1.6 (2006).

I found this 2007 thread on Komodo's page, nothing seems to have changed from there:
http://community.activestate.com/forum-topic/configuring-komodo-ruby-rails-and-code-completion

Thanx for reporting!

**Comment by spectacles** [comment]
I also added a hack which (for the first time in history) makes it possible to actually use the "rails" catalog. You can now activate it by simply adding this to your configs:

```
"codeintel_language_settings":
{
	 "Ruby": {
...
	 	  "codeintel_selected_catalogs": ["rails"],
...
	 }
},
```

**Comment by xskif** [comment]
Thank you.
I need to configure `.codintel/config` to specify rails catalog on `codeintel_selected_catalogs`?

**Comment by spectacles** [comment]
The file you are mentioning is neither used by CodeComplice nor by the current version of SCI. You can define your settings in your user settings of CC **or** in your sublime-project settings. Please study the read me file for more details!

**Comment by xskif** [comment]
Ok, i need to specify full path to the rails bin, or just `["rails"]` ?

**Comment by wizza-smile** [comment]
hey @xskif, I added two more commits for Ruby. Could you please download and give feedback, things should work better now!

all the best!

**Comment by xskif** [comment]
@wizza-smile , thank you. I will try it ASAP. It would be great, if i can download it by pacakge control.

**Comment by xskif** [comment]
> These are my complete settings for Ruby:

i'm install ruby and rails by RVM. My Ruby bin path is: `/home/skif/.rvm/rubies/ruby-2.1.5/bin/ruby`
And rails path is: `/home/skif/.rvm/gems/ruby-2.1.5/bin/rails`

**Comment by xskif** [comment]
Just downloaded and checked new version.
`Time.now` - is ok.
`1.hour.from_now` - didn't work autocompletion for `from_now` method.

**Comment by spectacles** [comment]
Same here! The link I posted above stated that Komodo cannot resolve function calls. If you can convince me that Komodo Edit offers a completion that CodeComplice does not, I will look into it again.

**Comment by xskif** [comment]
@spectacles , ok. So, tell me why i need to config `"codeintel_selected_catalogs": ["rails"]`? I don't understand that.

**Comment by spectacles** [comment]
with rails catalog enabled you will get additional completions like these:

http://de.tinypic.com/r/eq8j9z/8

**Comment by xskif** [comment]
@spectacles , got it, but i have index updating every time when i write `ActiveRecord::`

**Comment by spectacles** [comment]
okay, please open a new issue!
