### ISSUE TITLE
stuck at `Info: Update indexing..`/ `Info: processing PHP: please wait` and not show suggestions.

### ISSUE THREAD

**Issue by ptcong** [spectacles/CodeComplice#32]
@wizza-smile 
When i working on Xenforo, even is first time or N time i open the project. when i request `ctrl + space` suggestions, status bar display `Info: processing..` and not hint suggestions.
If i typing fast, feeling SublimeText make high CPU and text typing is very slow - lag. (often issues when i working on vBulletin project)

Even when i type `if($_SE` and request for `if($_SERVER...` *(that defined in CodeCompilce - CC std lib)* sometimes have no suggestions. >"< sometimes it when i type slow it show @@.

For `Info: Update indexing` or `Info: processing...PHP: please wait` in first time opened project, after a few seconds, it show `Timeout`.

Is working with large source like Xenforo include Zend, CC have problem while indexing/processing ?

You can try with Xenforo source code, and open any php file, then type `if($_SE)` .. first time or N time, it often no display suggestions.
For high CPU problem, you should try with vBulletin source code, open any file and type 
```
if($_GET['abc']) {
echo 123;
exit;
}
```
should type this fast and see it.

**Comment by wizza-smile** [comment]
hi @ptcong ! please check my latest post in this issue:
https://github.com/spectacles/CodeComplice/issues/17

You are probably indexing too many directories!

Feel free to post the contents of your php file here, so I can have a look!

Have a nice day!

**Comment by ptcong** [comment]
Yes @wizza-smile the project have many directories and files. 
But i have wait for CC update indexing and processing, but it show the message again and again. 
When typing fast, i feeling lag - text rendering slow.
The problem is not by php file, because even i try to create new file in the project and the issue still come.
Is possible to make the indexing/processing run in other thread ?

I just read your post. If i exclude a folder, is all its children will excluded too ?
And CC will not suggest what in the folders ?

**Comment by wizza-smile** [comment]
Hello @ptcong , long time!

Yes, if you exclude a directory, all the children will be excluded as well. In fact, the exclude settings works with regex. So if you exclude "/min/" for example, the ALL directories in the whole project whose absolute path contains "/min/" at some point, will be excluded.

Please use the `Dump import Dirs` Command to investigate, what directories actually get scanned.

Please read up this issue to get some more ideas what might be wrong with your project:
https://github.com/spectacles/CodeComplice/issues/17

take care!
