### ISSUE TITLE
CodeComplice.py, line 98, in <module> from codeintel2.common import CodeIntelError, EvalTimeout, LogEvalController, TRG_FORM_CPLN, TRG_FORM_CALLTIP, TRG_FORM_DEFN

### ISSUE THREAD

**Issue by 72CZR** [spectacles/CodeComplice#34]
Update 1.1.3 broke everything on every copy of Sublime Text I use (v3 on all)
Downgraded to 1.1.2 and works ok.
```
"CodeComplice.py", line 98, in <module>
    from codeintel2.common import CodeIntelError, EvalTimeout, LogEvalController, TRG_FORM_CPLN, TRG_FORM_CALLTIP, TRG_FORM_DEFN
ImportError: No module named 'codeintel2'
Unable to parse binding {caption: Tag: Lint Selection or Document, command: tag_lint}
```

Logs before that one:
```
reloading plugin CodeComplice.CodeComplice
Traceback (most recent call last):
  File "sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
```

**Comment by spectacles** [comment]
Well thanx for reporting! I'm afraid, this import error does not make sense to me. Absolutely nothing has changed regarding to that. Did you mind to delete the CodeComplice folder all together from /packages and re-install from packagecontrol? 

What's your OS('s)?

greetings

**Comment by 72CZR** [comment]
Hehe did that a couple of times. Tryied reinstalling with fresh config too using both package manager or fetching archive from here. Same results. 1.1.3 won't work.
I spent maybe half an hour checking what changed between versions and I couldn't find anything relevant to what may have caused this.
OS: Win 8.1 x64 on both PCs
Sublime version 3084 (Dev Channel)
Will try using a fresh portable Sublime non-dev version today and report back here.

**Comment by 72CZR** [comment]
Seems to work on another installation (almost identical build, 1.1.3 on ST3 3084). Same settings, same packages installed.
Does CodeComplice interfere with SublimeCodeIntel ? this installation has it installed but disabled. Others don't have it at all

**Comment by spectacles** [comment]
I shouldn't be any problems as long as SublimeCodeIntel is in disabled_packages. But you never know. Does it start working when you remove SublimeCodeIntel?

**Comment by 72CZR** [comment]
Well, seems I can't reproduce the original problem. Only thing I could do was install SublimeCodeIntel which broke my package manager untill I removed CodeIntel again :)
CodeComplice wouldn't work with CodeIntel installed & enabled (which is obvious). Don't know if it would work with it installed & disabled but I don't care anymore.
It works now, it just works ..
