### ISSUE TITLE
Change ctrl-click assignment

### ISSUE THREAD

**Issue by plazareff** [spectacles/CodeComplice#45]
Is it just me or contextual menu is no longer available after installation of CodeComplice ?

How can I change the "Jump to definition" key ?

Self reply: found it in the Default (OSX).sublime-mousemap

This should not be the default behaviour, imho. Still posting the issue in case it helps someone

**Comment by zmip** [comment]
I'm wondering: what do you think should be the default behaviour? I'd say command-click on MacOS, like in the olden days of CodeWarrior.
