### ISSUE TITLE
[Bug] autocomplete global, environment variables

### ISSUE THREAD

**Issue by ptcong** [spectacles/CodeComplice#5]
Hi @wizza-smile,

When i want to use an element of $_SERVER variable, it suggest `$DOCUMENT_ROOT`
the code become to `$_SERVER['$DOCUMENT_ROOT']` It is not correct. It should be `$_SERVER['DOCUMENT_ROOT']`.
And some keys are missing, eg: HTTP_REFERER.

Could you resolve this (should check $_SERVER, $_REQUEST, $_ENV);

**Comment by wizza-smile** [comment]
I pushed a commit that fixes the `$`issue, so you can download the zip and check that out. Thanx for the report!

Regarding your other requests:

Please look inside the directory `CodeComplice/libs/codeintel2/stdlibs/`!
There you will find the *.cix files that a responsible for these kind of completions. If you look at line 6219 in `php-5.5.cix` for example, you will find `$_SERVER` and all the inner variables that are defined in the array.
Feel free to add any entries you would like to see there, for example:

```
<variable citdl="string" name="HTTP_REFERER" />
```

So the completions in this case are quite static. Since `$_ENV` is dependent on your personal environment, you could also add completions for yourself there, too.

`$_REQUEST` is completely dynamic and there is no way to know what kind variables will be available at runtime. Let me know if I'm getting you wrong somewhere.

greetings

**Comment by ptcong** [comment]
I just added the lines to `php-5.5.cix` file, i think you should add it to the plugin, not only me need it.
The plugin should used by all people, it should suggest what php have, some keys not available on some hosting that based on server configuration, not php. Developer can upload his code to other server that have `HTTP_REFERER` right ?

$_ENV, $_REQUEST that dependent on personal environment and request. Don't need improve it.

```xml
<variable citdl="string" name="HTTP_REFERER" />
<variable citdl="string" name="HTTPS" />
<variable citdl="string" name="PATH_INFO" />
<variable citdl="string" name="ORIG_PATH_INFO" />
<variable citdl="string" name="AUTH_TYPE" />
<variable citdl="string" name="PHP_AUTH_USER" />
<variable citdl="string" name="PHP_AUTH_PW" />
<variable citdl="string" name="PHP_AUTH_DIGEST" />
<variable citdl="string" name="REQUEST_TIME_FLOAT" />
<variable citdl="string" name="PATH_TRANSLATED" />
<variable citdl="string" name="REMOTE_HOST" />
<variable citdl="string" name="REDIRECT_REMOTE_USER" />
```

**Comment by wizza-smile** [comment]
@ptcong great job! I integrated your additions into PHP stdlibs.

**Comment by xskif** [comment]
>When i want to use an element of $_SERVER variable, it suggest $DOCUMENT_ROOT
the code become to $_SERVER['$DOCUMENT_ROOT'] It is not correct. It should be $_SERVER['DOCUMENT_ROOT'].

There is the same porblem but with static class variables.
```php
Yii::$ap + tab (complete like Yii::$$app)
```

**Comment by spectacles** [comment]
@xsif can you tell me what is visible in the completion-box?
Does it say:
`$app (variable)`
or ist it
`$app (static property)`
?

**Comment by xskif** [comment]
static property

**Comment by spectacles** [comment]
You have some old version. Please make sure you have the latest version of CodeComplice installed!

**Comment by xskif** [comment]
Package Control says:
There are no packages ready for upgrade

**Comment by spectacles** [comment]
HI @ptcong, could you please confirm this bug?

**Comment by xskif** [comment]
>[static variables get double $$ when completion is triggered]
it's get double `$` only if i already typed `$` myself, see my first comment in this issue

**Comment by spectacles** [comment]
While in a PHP file:
In Sublime->Preferences->Settings More->SyntaxSpecific User
what do you see?

**Comment by xskif** [comment]
empty file

**Comment by spectacles** [comment]
That's the problem. Fill it with this:
``` 
{
    // Characters that are considered to separate words
    "word_separators": "\\./()\"'-:,.;<>~!@#%^&*|+=[]{}`~?",
}
```

**Comment by xskif** [comment]
i have this setting in Default Settings
```json
// Characters that are considered to separate words
    "word_separators": "./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}`~?",
```

**Comment by spectacles** [comment]
Thats fine for your default settings. But in PHP you should remove the `$`.

**Comment by xskif** [comment]
i think, you misunderstand the issue. Plugin autocomplete static property with `$` symbol, and it don't care if i already typed that symbol myself.

>Thats fine for your default settings. But in PHP you should remove the $.

why i should do that? simple variables like `$product` completing correctly.

**Comment by spectacles** [comment]
There is a way to "fix" this for the user. I consider doing so in the future.

**Comment by ptcong** [comment]
I confirmed the issue double `$` while autocomplete static property if i type `self::$te`, it complete `self::$$test`.

**Comment by wizza-smile** [comment]
@ptcong well it's not a bug really. You have to configure Sublime to detect the word borders in PHP correctly. 
Here is a link with further information regarding this issue:
http://sublimetexttips.com/fix-sublime-text-selection-php-sass-variables/

**Comment by ptcong** [comment]
Ok, resolved the issue

**Comment by ptcong** [comment]
@wizza-smile 
Have a problem with worlds selection, if i use `"word_separators": "./\\()\"'-:,.;<>~!@#%^&*|+=[]{}`~?",` for `PHP.sublime-settings` file. 
In a PHP file, have some `$name` variable, before modified `word_separators`, when i double click to a variable, ST highlight all vars with same name. But after, it highlight only one

**Comment by spectacles** [comment]
unfortunately this is a bug in SublimeText and can not be fixed by CodeComplice.

http://www.sublimetext.com/forum/viewtopic.php?f=3&t=15859

You can use the workaround described here:
http://stackoverflow.com/questions/25613424/double-click-highlight-variable-sublime-text-3-include

HTH

**Comment by ptcong** [comment]
ok, must wait ST to fix if they see the issue.
Thank u

**Comment by ptcong** [comment]
https://github.com/SublimeText/WordHighlight
This plugin resolved world/variable selection in PHP

**Comment by wizza-smile** [comment]
groovy!
