### ISSUE TITLE
"codeintel_live_disabled_languages" setting is ignored

### ISSUE THREAD

**Issue by charlesroper** [spectacles/CodeComplice#6]
See this issue for further details: https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/474#issuecomment-72197021

**Comment by spectacles** [comment]
`"codeintel_live_disabled_languages"` doesn't exist anymore. You can disable a particular language by setting `"codeintel_live"`to false for that language only. For Example:
```
{
    "codeintel_live":true,
    "codeintel_language_settings": {
        "PHP":{
           "codeintel_live":false
        }
   }

}
```

Additionally you have the option to remove certain sublime_scopes from triggering live completions.

For that use the setting `"codeintel_exclude_scopes_from_complete_triggers"`. Here you can define a list of scopes that will be excluded. For example:
`"codeintel_exclude_scopes_from_complete_triggers":["comment", "string", "markdown"]`

If you feel unsure about what exactly sublime_scopes are, please find your key-binding for the sublime command `show_scope_name` ! That will teach you everything you need.

If you have further questions or a proposal how to improve the current possibilities, please go ahead!

**Comment by charlesroper** [comment]
Sorry for the delay in replying - I just got around to testing this and it works great. I used the `"codeintel_exclude_scopes_from_complete_triggers"` setting. Many thanks for the help! :+1:
