### ISSUE TITLE
Coffeescript?

### ISSUE THREAD

**Issue by nfour** [spectacles/CodeComplice#8]
Hi! First of all, excited to see more code intelligence plugin development.

I'm struggling to find Coffeescript codeintel support. 

[CoffeeComplete Plus](https://packagecontrol.io/packages/CoffeeComplete%20Plus%20%28Autocompletion%29) technically works. The problem is it's abandoned and has glaring bugs that make it mostly unusable. Though, that plugin seems to literally be the best chance at codeintel autocompletion for CS across IDE's like; Visual Studio, Komodo, Webstorm, Light Table, Atom. They all don't support it in any capacity.

Is there something about Coffeescript that makes it difficult to build this kind of functionality for? It seems to be rather popular otherwise (eg. Atom).

Relates to https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/87

**Comment by spectacles** [comment]
Well yes, your assumption is right! JavaScript itself is a highly dynamic language, both in its nature and current development. That is what makes it a challenge for codeIntel. 
CodeComplice is already not doing too great at JavaScript. As soon as you start doing "interesting" stuff, the parser will fail to analyse in a useful way. CoffeeScript being the "interesting" sister of JavaScript, is certainly not an easier task! 
If you are hip enough to use CoffeeScript, you are hip enough to do without this plugin!
